services:
  - type: worker
    name: zer0-discord-bot
    env: node
    plan: free
    rootDir: zer0-bot
    buildCommand: npm ci
    startCommand: node deploy-commands.js && npm start
    
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
